resolver: nightly-2021-07-23
packages:
- '.'
local-bin-path: .
extra-deps:
- git: https://github.com/ConferOpenSource/composite
  commit: 312040be1e377bfc5e859478f24ebbb0283b3bf2
  subdirs:
  - composite-base
- git: https://gitlab.com/homotopic-tech/techlab
  commit: 88f77113eefb038ae33d1db353a8fbad704a67ad
- exceptions-0.10.4
- shh-0.7.1.4
- type-errors-pretty-0.0.1.1
- git: https://github.com/xmonad/xmonad
  commit: 13849c6230188cfbc303348ea3b374be4b60b655
- git: https://github.com/xmonad/xmonad-contrib
  commit: e30269fe96cb8d6498569e995835f66d78bceca1 
- git: https://github.com/xmonad/xmonad-extras
  commit: 6df82de88474754bc90724251d5fcbeccccbd7e7
allow-newer: true
nix:
  enable: true
  pure: false
  packages: [alsaLib, x11, xorg.libXrandr, xorg.libXScrnSaver, pkg-config]
